### ISSUE TITLE
fix downloading issue

### ISSUE THREAD

**Issue by wowk** [pthien92/qRFCViewer#1]
<pre>
diff --git a/src/rfcloader.cpp b/src/rfcloader.cpp
index 9e6585c..0f4e9b2 100755
--- a/src/rfcloader.cpp
+++ b/src/rfcloader.cpp
@@ -38,7 +38,7 @@ QRFCLoader::QRFCLoader(QObject *parent)
   m_qDir = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation) + "/qRFCView";
   QDir dir = QDir(m_qDir);
   dir.mkpath(m_qDir);
-  QUrl url = QUrl(QString("http://www.ietf.org/rfc/"));
+  QUrl url = QUrl(QString("https://www.ietf.org/rfc/"));
   SetDownloadURL(url);
   m_iCurrentRequestID=-1;
 }
@@ -61,12 +61,15 @@ void QRFCLoader::GetFile(uint32_t iRFCNum)
   QString qFilename;
   
   qFilename = m_qDir + "/rfc" + QString::number(iRFCNum) +".txt";
-  if ( QFile::exists( qFilename ) )
+
+  QFile file(qFilename);
+  if ( file.isOpen() && file.size() > 0  )
   {
+    file.close();
     emit done(qFilename);
     return;
-  }    
-  
+  }
+
   // RFC is not yet loaded
   // Open a file in the default dir.      
   RFCDesc_t sRFCDesc;
@@ -81,9 +84,9 @@ void QRFCLoader::GetFile(uint32_t iRFCNum)
      
      return;
   }    
-  QString qUrl= QString("http://") + m_qIETFSite + m_qIETFPath + QString("rfc%1.txt").arg(iRFCNum, 4, 10, QChar('0'));
-  
+  QString qUrl= QString("https://") + m_qIETFSite + m_qIETFPath + QString("rfc%1.txt").arg(iRFCNum, 4, 10, QChar('0'));
   
+
   qDebug() << qUrl;
 
   QNetworkRequest request(qUrl);
</pre>

**Comment by pthien92** [comment]
thanks @wowk, I have published a new release tailored for this fix.
Cheers
